package indi.bootis.vtodo.account.model;

import java.io.Serializable;
import java.util.Date;

public class Account implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.name_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.phone_number_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.active_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.member_since_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    private Date memberSince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password_hash_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    private String passwordHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.photo_url_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id_
     *
     * @return the value of account.id_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public Account withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id_
     *
     * @param id the value for account.id_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.name_
     *
     * @return the value of account.name_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public Account withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.name_
     *
     * @param name the value for account.name_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.email_
     *
     * @return the value of account.email_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public Account withEmail(String email) {
        this.setEmail(email);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.email_
     *
     * @param email the value for account.email_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.phone_number_
     *
     * @return the value of account.phone_number_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public Account withPhoneNumber(String phoneNumber) {
        this.setPhoneNumber(phoneNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.phone_number_
     *
     * @param phoneNumber the value for account.phone_number_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.active_
     *
     * @return the value of account.active_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public Account withActive(Boolean active) {
        this.setActive(active);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.active_
     *
     * @param active the value for account.active_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.member_since_
     *
     * @return the value of account.member_since_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public Date getMemberSince() {
        return memberSince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public Account withMemberSince(Date memberSince) {
        this.setMemberSince(memberSince);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.member_since_
     *
     * @param memberSince the value for account.member_since_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public void setMemberSince(Date memberSince) {
        this.memberSince = memberSince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password_hash_
     *
     * @return the value of account.password_hash_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public Account withPasswordHash(String passwordHash) {
        this.setPasswordHash(passwordHash);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password_hash_
     *
     * @param passwordHash the value for account.password_hash_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash == null ? null : passwordHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.photo_url_
     *
     * @return the value of account.photo_url_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public Account withPhotoUrl(String photoUrl) {
        this.setPhotoUrl(photoUrl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.photo_url_
     *
     * @param photoUrl the value for account.photo_url_
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sun Aug 11 20:52:52 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", email=").append(email);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", active=").append(active);
        sb.append(", memberSince=").append(memberSince);
        sb.append(", passwordHash=").append(passwordHash);
        sb.append(", photoUrl=").append(photoUrl);
        sb.append("]");
        return sb.toString();
    }
}