server:
  address: localhost
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: account-service
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev
      label: master