spring:
  datasource:
    url: jdbc:mysql://192.168.23.100:3306/vtodo
    password: vtodo
    username: vtodo

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    non-secure-port: 80
    appname: account-service
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka